/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jerry_mobile_HelloWorldJNI */

#ifndef _Included_com_jerry_mobile_HelloWorldJNI
#define _Included_com_jerry_mobile_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.jerry.mobile_HelloWorldJNI
 * Method:    getCLangString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring
JNICALL Java_com_jerry_mobile_HelloWorldJNI_getJniString(JNIEnv *, jclass clazz,jstring);

JNIEXPORT jint
JNICALL Java_com_jerry_mobile_HelloWorldJNI_addNum(JNIEnv *, jobject clazz);

JNIEXPORT void
JNICALL Java_com_jerry_mobile_HelloWorldJNI_accessStaticField(JNIEnv *, jobject clazz);


JNIEXPORT void
JNICALL Java_com_jerry_mobile_HelloWorldJNI_accessPrivateField(JNIEnv *, jobject clazz);


#ifdef __cplusplus
}
#endif
#endif